// <auto-generated />
using System;
using CheepRepository;
using Chirp.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CheepRepository.Migrations
{
    [DbContext(typeof(ChirpContext))]
    partial class ChirpDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("Chirp.Chirp.Core.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("Chirp.Chirp.Core.Cheep", b =>
                {
                    b.Property<Guid>("CheepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.HasKey("CheepId");

                    b.HasIndex("UserId");

                    b.ToTable("Cheeps");
                });

            modelBuilder.Entity("Chirp.Chirp.Core.Follower", b =>
                {
                    b.Property<Guid>("FollowerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FolloweeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FolloweeAuthorAuthorId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FollowerAuthorAuthorId")
                        .HasColumnType("TEXT");

                    b.HasKey("FollowerId", "FolloweeId");

                    b.HasIndex("FolloweeAuthorAuthorId");

                    b.HasIndex("FollowerAuthorAuthorId");

                    b.ToTable("Follower");
                });

            modelBuilder.Entity("Chirp.Chirp.Core.Cheep", b =>
                {
                    b.HasOne("Chirp.Chirp.Core.User", "User")
                        .WithMany("Cheeps")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chirp.Chirp.Core.Follower", b =>
                {
                    b.HasOne("Chirp.Chirp.Core.User", "FolloweeUser")
                        .WithMany()
                        .HasForeignKey("FolloweeAuthorAuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chirp.Chirp.Core.User", "FollowerUser")
                        .WithMany()
                        .HasForeignKey("FollowerAuthorAuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FolloweeUser");

                    b.Navigation("FollowerUser");
                });

            modelBuilder.Entity("Chirp.Chirp.Core.User", b =>
                {
                    b.Navigation("Cheeps");
                });
#pragma warning restore 612, 618
        }
    }
}
