name: Publish

on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
        
      - name: Build Linux
        run: |
          tag=$(git describe --tags --abbrev=0)
          release_name="Chirp-$tag-linux-x64"
          
          # Build file
          dotnet publish src/ITU-BDSA23-GROUP27.Chirp.CLI/ITU-BDSA23-GROUP27.Chirp.CLI.csproj --framework net7.0 --runtime "linux-x64" -c Release -o "$release_name" -p:PublishSingleFile=true --self-contained false /p:DebugType=None
          
          # Pack file
          7z a -tzip "${release_name}.zip" "./${release_name}/*"
          
          # Delete output directory
          rm -r "$release_name"
        shell: bash
          
      - name: Build Windows
        run: |
          tag=$(git describe --tags --abbrev=0)
          release_name="Chirp-$tag-win-x64"
          
          # Build file
          dotnet publish src/ITU-BDSA23-GROUP27.Chirp.CLI/ITU-BDSA23-GROUP27.Chirp.CLI.csproj --framework net7.0 --runtime "win-x64" -c Release -o "$release_name" -p:PublishSingleFile=true --self-contained false /p:DebugType=None
          
          # Pack file
          7z a -tzip "${release_name}.zip" "./${release_name}/*"
          
          # Delete output directory
          rm -r "$release_name"
        shell: bash
          
      - name: Build MacOS
        run: |
          tag=$(git describe --tags --abbrev=0)
          release_name="Chirp-$tag-osx-x64"
          
          # Build file
          dotnet publish src/ITU-BDSA23-GROUP27.Chirp.CLI/ITU-BDSA23-GROUP27.Chirp.CLI.csproj --framework net7.0 --runtime "osx-x64" -c Release -o "$release_name" -p:PublishSingleFile=true --self-contained false /p:DebugType=None
          
          # Pack file
          7z a -tzip "${release_name}.zip" "./${release_name}/*"
          
          # Delete output directory
          rm -r "$release_name"
        shell: bash
        
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v2.0.0 # Update with your desired version
          release_name: Release 1.0.0
          body: Release notes and description go here
        
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "Chirp*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}